name = "app"
version = "1.0.0"
dev-dependencies = { lustre_dev_tools = ">= 2.0.0 and < 3.0.0" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre_platform = { path = "../../../" }
gleam_json = ">= 2.3.0 and < 4.0.0"
formal = ">= 3.0.0 and < 4.0.0"
