name = "lustre"
version = "2.0.0"

target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["MIT"]
description = "A framework for building web apps - powered by Gleam and React!"
repository = { type = "github", user = "hayleigh-dot-dev", repo = "gleam-lustre" }
links = [{ title = "Website", href = "https://hayleigh-dot-dev.github.io/gleam-lustre" }]

[dependencies]
gleam_stdlib = "~> 0.28"

[dev-dependencies]
gleeunit = "~> 0.6"
