name = "lustre"
version = "3.1.3"
gleam = ">= 0.33.0"

description = "An Elm-inspired framework for building single page applications and server-rendered components in Gleam!"
repository = { type = "github", user = "lustre-labs", repo = "lustre" }
licences = ["MIT"]

links = [
  { title = "Website", href = "https://lustre.build" },
  { title = "Examples", href = "https://github.com/lustre-labs/lustre/tree/main/examples" },
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

internal_modules = [
  "lustre/cli",
  "lustre/cli/*",
  "lustre/internals",
  "lustre/internals/*",
]

[documentation]
pages = [
  { title = "CLI reference", path = "#", source = "" },
  { title = " ", path = "#", source = "" },
  { title = "Quickstart guide", path = "guide/01-quickstart.html", source = "./docs/guide/01-quickstart.md" },
  { title = "Managing state", path = "#", source = "" },
  { title = "Side effects", path = "#", source = "" },
  { title = "Server-side rendering", path = "#", source = "" },
  { title = "Components", path = "#", source = "" },
  { title = "Server components", path = "#", source = "" },
  { title = " ", path = "#", source = "" },
  { title = "Using with Wisp", path = "#", source = "" },
  { title = "Using with Glen", path = "#", source = "" },
  { title = "Using with Mist", path = "#", source = "" },
  { title = " ", path = "#", source = "" },
  { title = "For Elm developers", path = "#", source = "" },
  { title = "For React developers", path = "#", source = "" },
  { title = "For LiveView developers", path = "#", source = "" },
]

[dependencies]
argv = "~> 1.0"
filepath = "~> 0.1"
gleam_community_ansi = "~> 1.4"
gleam_erlang = "~> 0.23"
gleam_json = "~> 0.7"
gleam_otp = "~> 0.8"
gleam_stdlib = "~> 0.34"
glint = "0.16.0-rc1"
justin = "~> 1.0"
shellout = "~> 1.5"
simplifile = "~> 1.4"
tom = "~> 0.3"
spinner = "~> 1.1"

[dev-dependencies]
birdie = "~> 1.0"
gleeunit = "~> 1.0"
