name = "lustre"
version = "3.1.3"

description = "An Elm-inspired framework for building single page applications and server-rendered components in Gleam!"
licences = ["MIT"]
repository = { type = "github", user = "lustre-labs", repo = "lustre" }
links = [
  { title = "Website", href = "https://lustre.build" },
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]
gleam = ">= 0.33.0"

internal_modules = [
  "lustre/internals",
  "lustre/internals/*",
  "lustre/try",
]

[dependencies]
gleam_erlang = "~> 0.23"
gleam_json = "~> 0.7"
gleam_otp = "~> 0.8"
gleam_stdlib = "~> 0.34"
gleam_community_ansi = "~> 1.4"
glint = "~> 0.14"
argv = "~> 1.0"

[dev-dependencies]
birdie = "~> 1.0"
gleeunit = "~> 1.0"
