name = "lustre"
version = "3.1.0"

description = "An Elm-inspired framework for building web apps in Gleam!"
licences = ["MIT"]
repository = { type = "github", user = "lustre-labs", repo = "lustre" }
links = [
  { title = "Website", href = "https://lustre.build" },
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]
gleam = ">= 0.32.0"

internal_modules = [
  "lustre/try",
]

[dependencies]
gleam_stdlib = "~> 0.34"
