name = "lustre"
version = "3.1.1"

description = "An Elm-inspired framework for building web apps in Gleam!"
licences = ["MIT"]
repository = { type = "github", user = "lustre-labs", repo = "lustre" }
links = [
  { title = "Website", href = "https://lustre.build" },
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]
gleam = ">= 0.33.0"

internal_modules = [
  "lustre/internals",
  "lustre/internals/*",
  "lustre/runtime",
  "lustre/try",
]

[dependencies]
gleam_erlang = "~> 0.23"
gleam_json = "~> 0.7"
gleam_otp = "~> 0.8"
gleam_stdlib = "~> 0.34"
