name = "lustre"
version = "5.5.2"
gleam = ">= 1.13.0"

description = "A Gleam web framework for building HTML templates, single page applications, and real-time server components."
repository = { type = "github", user = "lustre-labs", repo = "lustre" }
licences = ["MIT"]

links = [
    { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

internal_modules = ["lustre/internals/*", "lustre/runtime/*", "lustre/vdom/*"]

[documentation]
pages = [
    { title = "Announcements", path = "announcements.html", source = "./pages/announcements/index.md" },
    { title = "", path = "announcements/2026-02-16.html", source = "./pages/announcements/2026-02-16.md" },
    { title = "", path = "announcements/2026-01-10.html", source = "./pages/announcements/2026-01-10.md" },
    { title = "", path = "announcements/2025-04-19.html", source = "./pages/announcements/2025-04-19.md" },
    { title = "", path = "announcements/2025-05-18.html", source = "./pages/announcements/2025-05-18.md" },
    { title = "", path = "announcements/2025-06-23.html", source = "./pages/announcements/2025-06-23.md" },
    { title = "", path = "announcements/2025-08-08.html", source = "./pages/announcements/2025-08-08.md" },
    { title = "", path = "announcements/2025-10-05.html", source = "./pages/announcements/2025-10-05.md" },

    { title = "Changelog", path = "changelog.html", source = "./CHANGELOG.md" },
    { title = "Examples", path = "reference/examples.html", source = "./pages/reference/examples.md" },
    { title = "Â ", path = "#", source = "" },
    { title = "Quickstart guide", path = "guide/01-quickstart.html", source = "./pages/guide/01-quickstart.md" },
    { title = "Managing state", path = "guide/02-state-management.html", source = "./pages/guide/02-state-management.md" },
    { title = "Side effects", path = "guide/03-side-effects.html", source = "./pages/guide/03-side-effects.md" },
    { title = "Server side rendering", path = "guide/05-server-side-rendering.html", source = "./pages/guide/05-server-side-rendering.md" },
    { title = "Full stack applications", path = "guide/06-full-stack-applications.html", source = "./pages/guide/06-full-stack-applications.md" },
    { title = "Â ", path = "#", source = "" },
    { title = "SPA deployments", path = "guide/04-spa-deployments.html", source = "./pages/guide/04-spa-deployments.md" },
    { title = "Full stack deployments", path = "guide/07-full-stack-deployments.html", source = "./pages/guide/07-full-stack-deployments.md" },
    { title = "Â ", path = "#", source = "" },
    { title = "For Elm developers", path = "cheatsheets/elm.html", source = "./pages/reference/for-elm-devs.md" },
    { title = "For React developers", path = "cheatsheets/react.html", source = "./pages/reference/for-react-devs.md" },
    { title = "For LiveView developers", path = "cheatsheets/liveview.html", source = "./pages/reference/for-liveview-devs.md" },
]

[dependencies]
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 4.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
houdini = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
argv = ">= 1.0.2 and < 2.0.0"
birdie = "~> 1.0"
esgleam = ">= 1.0.0 and < 2.0.0"
exception = ">= 2.0.0 and < 3.0.0"
gleam_regexp = ">= 1.1.0 and < 2.0.0"
gleamy_bench = ">= 0.5.0 and < 1.0.0"
gleeunit = "~> 1.0"
pprint = ">= 1.0.4 and < 2.0.0"
shellout = "~> 1.6"
simplifile = "~> 2.0"
booklet = ">= 1.1.0 and < 2.0.0"
