name = "app"
version = "1.0.0"
dev-dependencies = { lustre_dev_tools = ">= 1.6.5 and < 2.0.0" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = { path = "../../../" }
formal = ">= 2.2.0 and < 3.0.0"
