name = "app"
version = "1.0.0"
dev-dependencies = { lustre_dev_tools = ">= 2.0.0 and < 3.0.0" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = { path = "../../../" }
gleam_time = ">= 1.1.0 and < 2.0.0"
gleam_community_maths = ">= 2.0.0 and < 3.0.0"
