name = "app"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_json = "1.0.1"
gleam_stdlib = "0.43.0"
lustre = "4.6.3"
lustre_ui = "~> 0.4"

[dev-dependencies]
gleeunit = "~> 1.0"
lustre_dev_tools = "~> 1.0"
