name = "app"
version = "1.0.0"
target = "javascript"
dev-dependencies = { lustre_dev_tools = ">= 1.6.5 and < 2.0.0" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = { path = "../../../" }
gleam_json = ">= 2.3.0 and < 3.0.0"
rsvp = ">= 1.0.2 and < 2.0.0"
