name = "app"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
lustre = { path = "../../" }
lustre_ui = "~> 0.4"
lustre_http = "~> 0.5.2"

[dev-dependencies]
gleeunit = "~> 1.0"
lustre_dev_tools = "~> 1.0"
